easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserController
            new:
                fields:
                    - 'username'
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: true } }
                    - 'isAdmin'
            edit:
                fields:
                    - 'username'
                    - { property: 'email', type: 'email' }
                    - 'isAdmin'
            show:
                fields: ['username', 'email', 'registeredAt', 'isAdmin', 'shortLinks']
        ShortLink:
            class: App\Entity\ShortLink
            controller: App\Controller\Admin\ShortLinkController
            form:
                fields:
                    - 'url'
    design:
        menu:
            - { label: 'Dashboard', url: '/dashboard', default: true }
            - User
            - ShortLink