easy_admin:
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserController
            new:
                fields:
                    - 'username'
                    - { property: 'email', type: 'email' }
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: true } }
                    - 'isAdmin'
            edit:
                fields:
                    - 'username'
                    - { property: 'email', type: 'email' }
                    - 'isAdmin'
        ShortLink:
            class: App\Entity\ShortLink
            controller: App\Controller\Admin\ShortLinkController
